// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// New Feature
export const CHANGE_FEATURE_TEXT = 'CHANGE_FEATURE_TEXT';
export const CHANGE_SPRINT_CYCLE = 'CHANGE_SPRINT_CYCLE';
export const CHANGE_ENVIRONMENTS = 'CHANGE_ENVIRONMENTS';
export const FEATURE_CREATED_SUCCESS = 'FEATURE_CREATED_SUCCESS';
export const RECIEVED_FEATURE_LIST = 'RECIEVED_FEATURE_LIST';
export const UPDATE_FEATURE = 'UPDATE_FEATURE';
